### ISSUE TITLE
TypeError: open: illegal type for path parameter

### ISSUE THREAD

**Issue by Elelytha** [atareao/Touchpad-Indicator#43]
When I start touchpad-indicator from terminal, this is what I get:

> <gettext.GNUTranslations object at 0x7ff314132668>
No LSB modules are available.
#####################################################
Distributor: Ubuntu
Description: GalliumOS 2.1
Release: 16.04
Codename: xenial
Architecture: x86_64
#####################################################

> Touchpad-Indicator version: 2.2.0-0extras19.04.1ubuntu1
Traceback (most recent call last):
  File "/usr/bin/touchpad-indicator", line 36, in <module>
    main()
  File "/usr/share/touchpad-indicator/touchpadindicator.py", line 723, in main
    TouchpadIndicator()
  File "/usr/share/touchpad-indicator/touchpadindicator.py", line 104, in __init__
    self.touchpad = Touchpad()
  File "/usr/share/touchpad-indicator/touchpad.py", line 76, in __init__
    self.touchpads = get_touchpads()
  File "/usr/share/touchpad-indicator/touchpad.py", line 68, in get_touchpads
    evDevDevice = evdev.InputDevice(device)
  File "/usr/lib/python3/dist-packages/evdev/device.py", line 93, in __init__
    self.fd = os.open(dev, os.O_RDWR | os.O_NONBLOCK)
TypeError: open: illegal type for path parameter

Do you have any ideas what could cause this error?

**Comment by caschbre** [comment]
I'm getting the same issue after the recent update.

**Comment by Elelytha** [comment]
This has been fixed as of v. 2.2.1-0extras19.04.0
