### ISSUE TITLE
name 'syslog' is not defined 

### ISSUE THREAD

**Issue by KarelWintersky** [atareao/Touchpad-Indicator#74]
Lubuntu, LXDE 

```
PythonArgs: ['/usr/bin/touchpad-indicator', '-l']
Traceback:
 Traceback (most recent call last):
   File "/usr/bin/touchpad-indicator", line 36, in <module>
     main()
   File "/usr/share/touchpad-indicator/touchpadindicator.py", line 713, in main
     device_list.list()
   File "/usr/share/touchpad-indicator/device_list.py", line 122, in list
     context.log_priority = syslog.LOG_EMERG
 NameError: name 'syslog' is not defined
UserGroups: adm cdrom dip input lpadmin plugdev sambashare sudo
_LogindSession: c2
```

WTF

**Comment by KarelWintersky** [comment]
Solution https://github.com/atareao/Touchpad-Indicator/pull/75
